name: Redeploy Service

on:
  push:
    branches:
      - master

jobs:
  redeploy:
    environment: Google Cloud-Auto deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Google Cloud Machine
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP << 'EOF'
          cd /home/$USER/private_bot
          git pull origin master
          source /home/$USER/private_bot/venv/bin/activate
          pip install -e .
          sudo systemctl restart private_bot.service
        EOF

